### ISSUE TITLE
Environment variables aren't loading in Rails 4.2

### ISSUE THREAD

**Issue by dcunited001** [bkeepers/dotenv#144]
I tried adding `dotenv` to my Gemfile with Rails 4.2 and the vars in `.env` weren't being loaded on initialization, either during or after the AppName::Application module block.

Also, when I tried adding the `dotenv-rails` gem, I was running into a nil error because Rails.root isn't defined until the AppName::Application block starts.  So i was getting a nil error in `Dotenv::Railtie.load` on line 17.

**Comment by bkeepers** [comment]
#158 fixed the issue with `Rails.root` being nil.

Let me know if anyone sees issues with 4.2 not working. I have a few 4.2 apps that are working great.

**Comment by davidsantoso** [comment]
Unfortunately, I still don't seem to be getting my ENV variables loaded from my .env file. Running Rails 4.2 and dotenv-rails 1.0.2. Any thing I might be missing? `Rails.root` is returning the proper path.

**Comment by bkeepers** [comment]
Can you post what you have for dotenv in your gemfile?

**Comment by davidsantoso** [comment]
Definitely.

```ruby
source 'https://rubygems.org'

ruby '2.1.3'

gem 'rails', '4.2.0'
gem 'pg'
gem 'jbuilder', '~> 2.0'
gem 'bcrypt', '~> 3.1.7'
gem 'unicorn'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'dotenv-rails', :groups => [:development, :test]

group :development do
  gem 'byebug'
  gem 'spring'
end
```
As a side note, using `gem 'dotenv-rails', :require => 'dotenv/rails-now'` causes the same error as the original issue comment of `undefined method 'join' for nil:NilClass` on line 17 of rails.rb.

**Comment by bkeepers** [comment]
If you try the latest unreleased version (add `:github => "bkeepers/dotenv"` to your gemfile and run `bundle update`) the exception should go away.

But that doesn't explain why it's not working without the require. What do you see if you add something like `FOO=test` to `.env`, and then inside of `config/application.rb`?

```ruby
class MyApplication < Rails::Application
  puts "FOO is #{ENV["FOO"].inspect}"
  …
end
```

**Comment by davidsantoso** [comment]
I got a `FOO is nil`. 

Adding `:github => "bkeepers/dotenv"` did fix it though.

**Comment by mpchlets** [comment]
I had this same issue and it was fixed after changing my Gemfile to:

`gem 'dotenv-rails', :github => "bkeepers/dotenv"`

**Comment by tbbooher** [comment]
Hmm .. . I'm not getting it to work:
#gemfile
```
source 'https://rubygems.org'
ruby '2.1.5'
group :development, :test do
  gem 'dotenv-rails', github: "bkeepers/dotenv"
end
```
#.env
```
OMNIAUTH_PROVIDER_KEY="12345"
```
in application.rb
```
Bundler.require(*Rails.groups)
Dotenv::Railtie.load
```
rails c
puts ENV['OMNIAUTH_PROVIDER_KEY']
-> 'xxxxx'
```
Not sure how to get the env to load correctly.

**Comment by tbbooher** [comment]
disregard: found i was loading a variable by the same name in my .zshrc

**Comment by x-ji** [comment]
Still not working for me on Rails 4.2.0... Installed the github version of this gem but the problem persisted. I had to manually add `Dotenv::Railtie.load` to my application.rb for it to load in time. Sorry but to me it isn't clear from the previous discussions whether `Dotenv::Railtie.load` is a required step, or is the newest version of the gem supposed to fix it already?

**Comment by nickjj** [comment]
Using Rails 4.2.1 and dotenv-rails 2.0.1 I experience the same issue where it's not loading env vars. No resolution atm. Dropping in `Dotenv::Railtie.load` doesn't fix it, neither does loading the gem at the top of my gemfile.

If I inspect `ENV` from inside my unicorn file, it contains no traces of anything set in my `.env` file.

**Comment by DemitryT** [comment]
I'm just loading "dotenv-rails" in my `application.rb file` as a workaround.

So, right after you load all of the rails dependencies, try adding `require 'dotenv-rails'`

**Comment by nickjj** [comment]
Requiring in dotev-rails also has no effect. I wonder what's up. I created and developed a bunch of apps with dotenv in the past, never had any issues until recently. It's a show stopper atm.

**Comment by bkeepers** [comment]
I know many people that are using `dotenv-rails` successfully with Rails 4.2. If it's not working for you, I don't think it's related to this issue, which was fixed in #158. In order for us to help you, please open a new issue with:

- Rails version
- dotenv version
- snippet from your gemfile that has `dotenv-rails`
- any other information about your app's bootstrap process that is unique
